baseurl      = "https://vonlou.dev"
title        = "Emanuelle Costa"
languageCode = "pt-br"
theme        = "hello-friend-ng"
paginate     = 10

defaultContentLanguage = "pt-br"
enableRobotsTXT = true
enableEmoji     = true

[author]
  name = "Emanuelle Costa"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02/01/2006"
  dateformNumTime = "02/01/2006 15:04"

  homeSubtitle = "---------"
  disableReadOtherPosts = true
  enableSharingButtons = true

  description = "Meu blog"
  keywords = "blog"
  images = [""]

[[params.social]]
  name = "github"
  url = "https://github.com/emevonlou"
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/emevonlou"
[[params.social]]
  name = "instagram"
  url = "https://instagram.com/emevonlou"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.pt-br]
    title = "Emanuelle Costa"
    subtitle = "Hello!"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leia outros posts"

    [languages.pt-br.params.logo]
      logoText = "$ 111111111"
      logoHomeLink = "/"
  [[menu.main]]
    identifier = "about"
    name       = "Sobre"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"